### PR TITLE
fix: Refactor new connection

### LINKED ISSUE #320: The activerecord-cockroachdb-adapter v7.1.0 throws an error when `use_follower_reads_for_type_introspection` is set to `true`
Your ruby gem activerecord-cockroachdb-adapter had a recent release to support rails 7.1. When using it, and the setting `use_follower_reads_for_type_introspection` = true, the error: "PG::FeatureNotSupported: ERROR: inconsistent AS OF SYSTEM TIME timestamp; expected: 1708547400.494068015,0, got: 1708547390.502956628,0
HINT: try SET TRANSACTION AS OF SYSTEM TIME" is raised from this line: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/9506aa79785e7e945ae86bc6579ce7330e38635e/lib/active_record/connection_adapters/cockroachdb_adapter.rb#L592

No application queries can execute, the error is triggered before they can run.

When setting `use_follower_reads_for_type_introspection` = false, there isn't any error.

**More info:** 
The error doesn't occur locally, it occurs using our qa cluster. And it appears the method that triggers it is `create_or_find_by!`
I think the error doesn't occur locally because its not a multi-region db, and it has different table localities.

I confirmed the error behavior in another application of ours too.

Weird thing is, not all rails models trigger it when calling `create_or_find_by!`.  My guess is that a unique index or foreign key might have something to do with which models trigger it? Hard to discern a pattern.

One other note: if the error doesn't occur first (isn't the first query run) it doesn't occur at all. Meaning, if I run some other query, then the offending `create_or_find_by!`, it doesn't throw an error.

Conversely, when the error does occur, all other subsequent queries will trigger an error. This error is different:

```
/home/code/vendor/bundle/ruby/3.2.0/gems/pg-1.5.5/lib/pg/result.rb:17:in `type_map=': wrong argument type nil (expected PG::TypeMap) (TypeError)

self.type_map = type_map
```

### PR DESCRIPTION
**Pull request by BuonOmo**
The old method was calling `AbstractAdapter#initialize` with a connection object, rather than a hash. This was then setting `@unconfigured_connection`, which in turns forced to re-run `#configure_connection` when a first query was made. This is usually OK (although unnecessary) except if `use_follower_reads_for_type_introspection` is used, since it sets AOST for a single query, which fails within a transaction.

Fixes #320

### CODE REVIEW

**Comment by dikshant** [comment]
This is great! Thanks for fixing!

File: Gemfile [hunk 1]
```diff
@@ -55,6 +55,7 @@ group :development, :test do
   gem "debug"
   gem "minitest-excludes", "~> 2.0.1"
   gem "minitest-github_action_reporter", github: "BuonOmo/minitest-github_action_reporter", require: "minitest/github_action_reporter_plugin"
+  gem "ostruct", "~> 0.6"
```
Comment (grantpaulson6) [inline Gemfile:58]: whats the reason for adding this?

Comment (BuonOmo) [reply Gemfile:58]: @grantpaulson6 ruby 3.5 stops shipping ostruct, it sends a ruby warning. And ruby warnings are errors in the rails test suite. See https://github.com/cockroachdb/activerecord-cockroachdb-adapter/actions/runs/8621739468/job/23631300792

File: lib/active_record/connection_adapters/cockroachdb_adapter.rb [hunk 2]
```diff
@@ -255,6 +235,21 @@ def self.database_exists?(config)
...
+      # since Cockroach will sometimes not raise until a query is made.
+      rescue ActiveRecord::StatementInvalid => error
+        no_db_err_check1 = @connection_parameters && @connection_parameters[:dbname] && error.cause.message.include?(@connection_parameters[:dbname])
+        no_db_err_check2 = @connection_parameters && @connection_parameters[:dbname] && error.cause.message.include?("pg_type")
+        if no_db_err_check1 || no_db_err_check2
+          raise ActiveRecord::NoDatabaseError
+        else
+          raise ActiveRecord::ConnectionNotEstablished, error.message
+        end
+      end
```
Comment (BuonOmo) [inline lib/active_record/connection_adapters/cockroachdb_adapter.rb:251]: This is also outdated compared to the rails db, and not tested in our database, and I don't know if _since Cockroach will sometimes not raise until a query is made._ is still valid and what if refers to. Do you have an idea of how to reproduce this behaviour @rafiss ?

**Comment by grantpaulson6** [comment]
@BuonOmo when do you think this change will be released?

**Comment by BuonOmo** [comment]
I don't know, it will depend on @rafiss' review. Besides that I think there's no issue

**Comment by grantpaulson6** [comment]
just bumping this @rafiss @BuonOmo would love to see it sooner rather than later

File: lib/active_record/connection_adapters/cockroachdb_adapter.rb (hunk 2 above)
Comment (rafiss) [reply lib/active_record/connection_adapters/cockroachdb_adapter.rb:251]: I am not sure, but a guess I have is that it refers to the fact that CRDB allows you to connect even if the connection string refers to a database name that does not exist. But when AR tries using that database name to do something, CRDB will return an error.

**Review by rafiss — APPROVED** [review]

**Comment by grantpaulson6** [comment]
@rafiss or @BuonOmo would you release this? We just had it happen in production and caused errors. It hosed a rails worker and we had to kill it

**Comment by BuonOmo** [comment]
I still don't have the permissions to do it, I'll ping @rafiss
