### PR TITLE
fix: handle indexes with a hidden compound

### LINKED ISSUE #344: Rails migration fails after upgrading from 24.1 to 24.2 - no indexes found & no support for composite primary keys
After upgrading from 24.1 to 24.2, there is a `no indexes found` error and a `no support for composite primary keys` when running rails migration. This seems to be happening exclusively on Regional by Row tables with PKs and indexes that include the hidden `crdb_region` column 

It looks like the culprit could be that the `crdb_region` column is now included in `pg_index.indkey`

**Issue 1**
```
== migrating ============================
-- remove_index(:redacted_table_name, "redacted_table_name_id", {:algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

No indexes found on redacted_table_name with the options provided.

Caused by:
ArgumentError: No indexes found on redacted_table_name with the options provided. (ArgumentError)
            raise ArgumentError, "No indexes found on #{table_name} with the options provided."
Tasks: TOP => db:migrate
```

**Issue 2**
```
WARNING: Active Record does not support composite primary key.
redacted_table_name has composite primary key. Composite primary key is ignored.
```

### PR DESCRIPTION
**Pull request by BuonOmo**
This fixes regional related parts, hence fixes #344

### CODE REVIEW

File: lib/active_record/connection_adapters/cockroachdb/schema_statements.rb [hunk 1]
```diff
@@ -55,6 +55,37 @@ def primary_key(table_name)
...
+        def column_names_from_column_numbers(table_oid, column_numbers)
+          return super unless database_version >= 24_02_02
+
+          Hash[query(<<~SQL, "SCHEMA")].values_at(*column_numbers).compact
+            SELECT a.attnum, a.attname
+            FROM pg_attribute a
+            WHERE a.attrelid = #{table_oid}
+            AND a.attnum IN (#{column_numbers.join(", ")})
+            AND NOT a.attishidden
+          SQL
```
Comment (mmalek-sa) [inline lib/active_record/connection_adapters/cockroachdb/schema_statements.rb:86]: This is not specific to CRDB >= 24.0.2. On 24.1.2 unique constraints on a region by row table will combine the `crdb_region` and column on the dumped schema. Since `attishidden` is not available in CRDB 24.1.2 this seems to do the trick:

```ruby
def column_names_from_column_numbers(table_oid, column_numbers)
  Hash[query(<<~SQL, "SCHEMA")].values_at(*column_numbers).compact
    SELECT a.attnum, a.attname
    FROM pg_attribute a
    WHERE a.attrelid = #{table_oid}
    AND a.attnum IN (#{column_numbers.join(", ")})
    AND a.attisdropped <> 't'
    AND a.attname <> 'crdb_region'
  SQL
end
```

Without `attisdropped <> t`, I see weird `....pg.dropped.18...` strings in the schema dump. All this is happening after upgrade to `Rails 7.1.x` and Cockroach AR Adapter `7.1.x`. I can't reproduce it on Rails `7.0.x`.

When it comes to `unique_constraints`, I also see a problem with indexes with expressions. For example:

```ruby
    t.index "lower(name::STRING) ASC", name: "index_table_name_redacted_on_name_unique", unique: true
```

is becoming:
```ruby
    t.unique_constraint [], name: "index_table_name_redacted_on_name_unique"
```

Comment (mmalek-sa) [reply lib/active_record/connection_adapters/cockroachdb/schema_statements.rb:86]: I created an issue with a workaround for `unique_constraint` [here](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/347).

Comment (BuonOmo) [reply lib/active_record/connection_adapters/cockroachdb/schema_statements.rb:86]: @mmalek-sa I'm not targetting `24.0.2` but `24.2.2`, which is the version where the related issue started raising. We do not need this patch before (hence the conditionnal!)

**Review by rafiss — APPROVED** [review]
nice, thanks for identifying the fix!
